#!/usr/bin/env python3
"""Inline the woff2 files from node_modules into src/fonts.css as data URIs.

A render worker then needs no font request at all, which keeps
document.fonts.load() from ever stalling mid-render.

    python3 scripts/inline-fonts.py
"""

import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "fonts.css")

FACES = [
    ("Anton", 400, "@fontsource/anton/files/anton-latin-400-normal.woff2"),
    ("Anton", 400, "@fontsource/anton/files/anton-latin-ext-400-normal.woff2"),
    ("Inter", 600, "@fontsource/inter/files/inter-latin-600-normal.woff2"),
    ("Inter", 700, "@fontsource/inter/files/inter-latin-700-normal.woff2"),
    ("Inter", 900, "@fontsource/inter/files/inter-latin-900-normal.woff2"),
    ("Montserrat", 600, "@fontsource/montserrat/files/montserrat-latin-600-normal.woff2"),
    ("Montserrat", 700, "@fontsource/montserrat/files/montserrat-latin-700-normal.woff2"),
]


def main():
    blocks = ["/* Generated by scripts/inline-fonts.py — do not edit by hand. */"]
    for family, weight, rel in FACES:
        path = os.path.join(ROOT, "node_modules", rel)
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        blocks.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: block;\n"
            f"  src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
            "}"
        )
    with open(OUT, "w") as f:
        f.write("\n\n".join(blocks) + "\n")
    print(f"wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} kB, {len(FACES)} faces)")


main()
